

export const A = [
    { palabra: "Amigo", significado: "una persona con la que uno tiene una relación de afecto y confianza." },
    { palabra: "Amar", significado: "sentir un gran afecto y cariño por alguien." },
    { palabra: "Avión", significado: "una máquina voladora más pesada que el aire, impulsada por uno o más motores." },
    { palabra: "Arena", significado: "un material granular que se compone de partículas pequeñas de roca, conchas y otros materiales." },
    { palabra: "Almohada", significado: "una almohada es un objeto blandito que se usa para apoyar la cabeza cuando se duerme." },
    { palabra: "Ardilla", significado: "una pequeña criatura mamífera que tiene una cola larga y una cola esponjosa." },
    { palabra: "Alegre", significado: "que siente o expresa alegría." },
    { palabra: "Alimento", significado: "cualquier sustancia que proporciona los nutrientes necesarios para la vida." },
    { palabra: "Aventura", significado: "una experiencia emocionante e inesperada." },
    { palabra: "Amanecer", significado: "el momento del día en que el sol comienza a salir por el horizonte." },
    { palabra: "Agricultura", significado: "el cultivo de plantas y el cuidado de los animales para obtener alimentos." },
    { palabra: "Abrazo", significado: "un gesto de afecto en el que dos personas se abrazan con los brazos." },
    { palabra: "Acuático", significado: "que vive en el agua." },
    { palabra: "Agua", significado: "un líquido incoloro, inodoro e insípido que es esencial para la vida." },
    { palabra: "Artista", significado: "una persona que crea obras de arte, como pinturas, esculturas, música o literatura." },
    { palabra: "Anillo", significado: "una pieza de joyería que se lleva en el dedo y que a menudo tiene forma de círculo." },
    { palabra: "Asombro", significado: "una sensación de asombro o sorpresa." },
    { palabra: "Atardecer", significado: "el momento del día en que el sol se pone por el horizonte." },
    { palabra: "Azul", significado: "un color que es similar al color del cielo y del mar." },
    { palabra: "Aroma", significado: "un olor agradable." },
    { palabra: "Abundante", significado: "que tiene mucho de algo." },
    { palabra: "Anaranjado", significado: "un color que es similar al color de las naranjas y los melones." },
    { palabra: "Adolescente", significado: "una persona que tiene entre 13 y 19 años de edad." },
    { palabra: "Antiguo", significado: "que existe desde hace mucho tiempo." },
    { palabra: "Astro", significado: "un cuerpo celeste, como un planeta, una estrella o una galaxia." },
    { palabra: "Aprender", significado: "adquirir conocimientos o habilidades." },
    { palabra: "Altura", significado: "la distancia desde el punto más bajo de algo hasta su punto más alto." },
    { palabra: "Abierto", significado: "que no está cerrado." },
    { palabra: "Aire", significado: "la mezcla de gases que rodea la Tierra." },
    { palabra: "Animal", significado: "un organismo vivo que no es una planta y que tiene un cuerpo con un esqueleto interno." },
    { palabra: "Amoroso", significado: "que siente o expresa amor." },
    { palabra: "Actividad", significado: "una acción o un proceso que se lleva a cabo." },
    { palabra: "Agregar", significado: "aumentar la cantidad de algo." },
    { palabra: "Adorable", significado: "que es muy agradable o encantador." },
    { palabra: "Árbol", significado: "una planta leñosa que tiene un tronco alto y ramas." },
    { palabra: "Acelerar", significado: "aumentar la velocidad de algo." },
    { palabra: "Anhelo", significado: "un deseo intenso de algo." },
    { palabra: "Aullido", significado: "un sonido agudo que hacen los lobos y otros animales." },
    { palabra: "Aldea", significado: "un pequeño pueblo." },
    { palabra: "Apetito", significado: "el deseo de comer." },
    { palabra: "Agotado", significado: "cansado o fatigado." },
    { palabra: "Adivinar", significado: "intentar descubrir algo sin tener información sobre ello." },
    { palabra: "Amable", significado: "que es cortés y considerado con los demás." },
    { palabra: "Alegría", significado: "una sensación de felicidad y satisfacción." },
    { palabra: "Anunciar", significado: "hacer público algo." },
    { palabra: "Armadura", significado: "una pieza de ropa protectora que se usa para proteger el cuerpo de lesiones." },
    { palabra: "Atleta", significado: "una persona que compite en deportes." },
    { palabra: "Adornar", significado: "decorar o embellecer algo." },
    { palabra: "Apretado", significado: "que está cerca o muy unido." },
    { palabra: "Aislado", significado: "que está separado o aislado de otros." }
];

export const B = [
    { palabra: "Bosque", significado: "una gran extensión de tierra cubierta de árboles" },
    { palabra: "Brillar", significado: "emitir luz" },
    { palabra: "Bucear", significado: "sumergirse bajo el agua para nadar o explorar" },
    { palabra: "Bola", significado: "una forma redonda" },
    { palabra: "Bicicleta", significado: "un vehículo de dos ruedas que se impulsa con los pies" },
    { palabra: "Bello", significado: "hermoso" },
    { palabra: "Barco", significado: "una embarcación que se utiliza para navegar por el agua" },
    { palabra: "Bebé", significado: "un recién nacido" },
    { palabra: "Bilingüe", significado: "que habla dos idiomas" },
    { palabra: "Blanco", significado: "el color de la nieve y la leche" },
    { palabra: "Brisa", significado: "una brisa ligera" },
    { palabra: "Bocado", significado: "una pequeña porción de comida" },
    { palabra: "Bastón", significado: "un palo largo que se usa para apoyarse al caminar" },
    { palabra: "Biblioteca", significado: "una colección de libros que se guarda en un edificio" },
    { palabra: "Burbuja", significado: "una esfera de gas rodeada de una fina película de líquido" },
    { palabra: "Bailar", significado: "moverse al ritmo de la música" },
    { palabra: "Banco", significado: "un asiento largo" },
    { palabra: "Botella", significado: "un recipiente cerrado de vidrio o plástico que se usa para contener líquidos" },
    { palabra: "Búho", significado: "un ave nocturna con grandes ojos" },
    { palabra: "Broma", significado: "una historia divertida" },
    { palabra: "Belleza", significado: "la cualidad de ser hermoso" },
    { palabra: "Burro", significado: "un mamífero domesticado con orejas largas y una cola larga" },
    { palabra: "Baloncesto", significado: "un deporte que se juega entre dos equipos de cinco jugadores cada uno, que intentan introducir una pelota en la canasta del equipo contrario" },
    { palabra: "Banderín", significado: "una pequeña bandera" },
    { palabra: "Beso", significado: "un gesto de cariño que consiste en poner los labios sobre los labios de otra persona" },
    { palabra: "Bulevar", significado: "una avenida ancha" },
    { palabra: "Botánico", significado: "una persona que estudia las plantas" },
    { palabra: "Broche", significado: "una joya que se usa para sujetar la ropa" },
    { palabra: "Botánica", significado: "la ciencia que estudia las plantas" },
    { palabra: "Batalla", significado: "un combate entre dos o más grupos de personas" },
    { palabra: "Bruja", significado: "una mujer que se cree que practica la magia" },
    { palabra: "Bolso", significado: "una bolsa que se lleva colgada del hombro o del brazo" },
    { palabra: "Brillo", significado: "el resplandor de algo que refleja la luz" },
    { palabra: "Borrar", significado: "eliminar algo escribiendo o pintando sobre ello" },
    { palabra: "Bocadillo", significado: "una comida ligera que se come entre horas" },
    { palabra: "Bloque", significado: "un objeto sólido de forma cúbica o rectangular" },
    { palabra: "Brújula", significado: "un instrumento que se utiliza para orientarse" },
    { palabra: "Buzón", significado: "un recipiente que se coloca en la calle para depositar el correo" },
    { palabra: "Bote", significado: "una embarcación pequeña" },
    { palabra: "Bufanda", significado: "una prenda de vestir que se lleva alrededor del cuello para abrigarse" },
    { palabra: "Bastidor", significado: "un marco de madera o metal que se utiliza para sostener la tela cuando se pinta" },
    { palabra: "Brincar", significado: "saltar" },
    { palabra: "Brocha", significado: "una herramienta que se utiliza para aplicar pintura" },
    { palabra: "Buitre", significado: "un ave carroñera" },
    { palabra: "Bombero", significado: "una persona que trabaja en un cuerpo de bomberos" },
    { palabra: "Bocanada", significado: "una cantidad de aire o líquido que se inspira o espira de una sola vez" },
    { palabra: "Bofetada", significado: "un golpe que se da con la mano abierta" },
    { palabra: "Botín", significado: "el robo o el saqueo" },
    { palabra: "Bizcocho", significado: "un pastel pequeño y esponjoso" },
    { palabra: "Bigote", significado: "el vello facial que crece sobre el labio superior" }
];

export const C = [{ palabra: "cielo", significado: "La atmósfera que rodea la Tierra" },
{ palabra: "correr", significado: "Moverse a gran velocidad con los pies" },
{ palabra: "caminar", significado: "Moverse a paso lento con los pies" },
{ palabra: "comida", significado: "Cualquier sustancia que proporciona los nutrientes necesarios para la vida" },
{ palabra: "corazón", significado: "Un órgano muscular que bombea sangre por todo el cuerpo" },
{ palabra: "castillo", significado: "Una gran estructura fortificada" },
{ palabra: "cálido", significado: "Que tiene una temperatura alta" },
{ palabra: "colina", significado: "Una elevación del terreno con una pendiente suave" },
{ palabra: "ciudad", significado: "Un área urbana grande con una población numerosa" },
{ palabra: "canto", significado: "El sonido que produce un pájaro u otro animal" },
{ palabra: "circular", significado: "Tener forma de círculo" },
{ palabra: "cebra", significado: "Un mamífero africano con rayas blancas y negras" },
{ palabra: "cerveza", significado: "Una bebida alcohólica hecha de cebada, lúpulo y levadura" },
{ palabra: "camión", significado: "Un vehículo grande con ruedas que se utiliza para transportar cargas pesadas" },
{ palabra: "caja", significado: "Un recipiente cerrado con una tapa" },
{ palabra: "cautivar", significado: "Atraer y mantener la atención de alguien" },
{ palabra: "cine", significado: "Un lugar donde se proyectan películas" },
{ palabra: "cisne", significado: "Un ave acuática grande con un cuello largo y una cola blanca" },
{ palabra: "capitán", significado: "El oficial al mando de un barco" },
{ palabra: "ciclismo", significado: "El deporte de montar en bicicleta" },
{ palabra: "cosecha", significado: "La recolección de cultivos" },
{ palabra: "cometa", significado: "Un objeto helado que orbita alrededor del Sol" },
{ palabra: "cuerpo", significado: "La estructura física de un ser vivo" },
{ palabra: "calma", significado: "La ausencia de actividad o movimiento" },
{ palabra: "curioso", significado: "Que siente curiosidad" },
{ palabra: "cocina", significado: "Una habitación de una casa donde se prepara la comida" },
{ palabra: "campana", significado: "Un objeto metálico que produce un sonido al ser golpeado" },
{ palabra: "cuento", significado: "Una historia corta" },
{ palabra: "calle", significado: "Una vía pública pavimentada que conecta diferentes partes de una ciudad" },
{ palabra: "cuadro", significado: "Una pintura o dibujo que se enmarca y se cuelga en una pared" },
{ palabra: "cactus", significado: "Una planta espinosa que crece en climas áridos" },
{ palabra: "conectar", significado: "Unir dos cosas" },
{ palabra: "criatura", significado: "Un ser vivo" },
{ palabra: "colores", significado: "Las cualidades que distinguen a los objetos por su apariencia" },
{ palabra: "crucero", significado: "Un viaje por mar" },
{ palabra: "cálido", significado: "Que tiene una temperatura agradable" },
{ palabra: "calcetín", significado: "Una prenda de vestir que se usa para cubrir los pies" },
{ palabra: "comedia", significado: "Una obra de teatro o película que tiene como objetivo hacer reír al público" },
{ palabra: "cautivar", significado: "Atraer y mantener la atención de alguien" },
{ palabra: "corriente", significado: "Un movimiento continuo de agua" },
{ palabra: "cruzar", significado: "Ir de un lado a otro de algo" },
{ palabra: "cepillo", significado: "Un objeto con cerdas que se utiliza para limpiar o aplicar algo" },
{ palabra: "calcular", significado: "Determinar el valor de algo mediante el uso de matemáticas" },
{ palabra: "crepúsculo", significado: "El período de tiempo entre el atardecer y el amanecer" },
{ palabra: "cuaderno", significado: "Un libro con páginas en blanco que se utiliza para escribir o dibujar" },
{ palabra: "cuerda", significado: "Un material flexible hecho de hilos o fibras trenzados" },
{ palabra: "caracol", significado: "Un molusco que tiene un caparazón en espiral" },
{ palabra: "cohete", significado: "Un vehículo propulsado por cohetes que se utiliza para volar en el espacio" },
{ palabra: "caja", significado: "Un recipiente cerrado con una tapa" },
{ palabra: "cofre", significado: "Un recipiente grande y cerrado que se utiliza para guardar objetos de valor" }
];

export const D = [{ palabra: "dibujo", significado: "Una representación visual de algo" },
{ palabra: "diamante", significado: "Una piedra preciosa que se caracteriza por su forma cúbica y su brillo" },
{ palabra: "deseo", significado: "Un anhelo o anhelo" },
{ palabra: "desayuno", significado: "La primera comida del día" },
{ palabra: "diversión", significado: "Una actividad que es agradable y entretenida" },
{ palabra: "dado", significado: "Un objeto pequeño y cúbico con seis caras numeradas del 1 al 6" },
{ palabra: "dulce", significado: "Un alimento que es agradablemente dulce" },
{ palabra: "dolor", significado: "Una sensación física desagradable causada por una lesión o enfermedad" },
{ palabra: "decisión", significado: "La elección de una cosa entre varias opciones" },
{ palabra: "destino", significado: "El lugar o condición a la que alguien o algo está destinado" },
{ palabra: "danza", significado: "Un movimiento corporal rítmico realizado como una forma de expresión o entretenimiento" },
{ palabra: "dedo", significado: "Una de las extremidades móviles y flexibles que se extienden desde la muñeca" },
{ palabra: "difícil", significado: "Que requiere mucha habilidad o esfuerzo" },
{ palabra: "duda", significado: "Una falta de certeza o confianza" },
{ palabra: "defensa", significado: "La acción de proteger a alguien o algo de daño" },
{ palabra: "dama", significado: "Una pieza de ajedrez que se mueve en forma de L" },
{ palabra: "diente", significado: "Una estructura dura que se encuentra en la boca y se utiliza para masticar" },
{ palabra: "deportivo", significado: "Relacionado con los deportes" },
{ palabra: "dormir", significado: "El estado de descanso profundo durante el cual la mente y el cuerpo están inactivos" },
{ palabra: "doctor", significado: "Una persona que ha completado un programa de educación médica y está autorizada para practicar medicina" },
{ palabra: "decorar", significado: "Hacer que algo sea más atractivo o agradable añadiendo elementos decorativos" },
{ palabra: "derramar", significado: "Perder líquido accidentalmente" },
{ palabra: "duna", significado: "Una colina de arena que se forma en las costas o en los desiertos" },
{ palabra: "diseño", significado: "El proceso de creación de un plan o esquema para algo" },
{ palabra: "descansar", significado: "Tomar un descanso del trabajo o la actividad" },
{ palabra: "desechar", significado: "Tirar algo que ya no se necesita o se quiere" },
{ palabra: "desfile", significado: "Una marcha pública de personas o vehículos, a menudo para celebrar un evento o ocasión especial" },
{ palabra: "dedicatoria", significado: "Una breve declaración escrita al comienzo de un libro o obra de arte, que expresa el agradecimiento del autor a una persona o personas" },
{ palabra: "dosis", significado: "La cantidad de una medicina o droga que se toma a la vez" },
{ palabra: "delgado", significado: "Que tiene una pequeña cantidad de grasa o carne" },
{ palabra: "depender", significado: "Confiar en alguien o algo para obtener apoyo o ayuda" },
{ palabra: "diferente", significado: "No igual a otra cosa" },
{ palabra: "decir", significado: "Expresar una idea o pensamiento con palabras" },
{ palabra: "desierto", significado: "Una región árida que tiene muy poca lluvia" },
{ palabra: "derrumbar", significado: "Caer o causar que algo caiga" },
{ palabra: "dieta", significado: "Un plan de alimentación diseñado para ayudar a las personas a perder peso, mantener un peso saludable o mejorar su salud" },
{ palabra: "dejar", significado: "Terminar de hacer algo o dejar de estar en un lugar" },
{ palabra: "despegar", significado: "Levantarse del suelo y comenzar a volar" },
{ palabra: "destacar", significado: "Ser más prominente o visible que otras cosas" },
{ palabra: "dado", significado: "Un objeto pequeño y cúbico con seis caras numeradas del 1 al 6" },
{ palabra: "desastre", significado: "Un evento que causa una gran destrucción o daño" },
{ palabra: "durar", significado: "Continuar durante un tiempo determinado" },
{ palabra: "decidir", significado: "Tomar una decisión sobre algo" },
{ palabra: "disfrutar", significado: "Encontrar placer en algo" },
{ palabra: "dolor", significado: "Una sensación física desagradable causada por una lesión o enfermedad" },
{ palabra: "difuminar", significado: "Hacer que algo sea menos claro o definido" },
{ palabra: "definir", significado: "Dar el significado de una palabra o frase" },
{ palabra: "devorar", significado: "Comer algo con gran rapidez y avidez" },
{ palabra: "dudar", significado: "No estar seguro de algo" }
];

export const E = [
    { palabra: "estrella", significado: "Un gran objeto celeste que brilla con su propia luz" },
    { palabra: "escuchar", significado: "Prestar atención a lo que alguien dice o hace" },
    { palabra: "elefante", significado: "Un mamífero grande con una trompa, orejas grandes y una piel gruesa" },
    { palabra: "esencia", significado: "La parte más importante o significativa de algo" },
    { palabra: "elegante", significado: "Que es bonito y elegante" },
    { palabra: "emoción", significado: "Una sensación fuerte que afecta al cuerpo y la mente" },
    { palabra: "espacio", significado: "El área que rodea a la Tierra o a cualquier otro objeto" },
    { palabra: "enseñar", significado: "Transmitir conocimientos o habilidades a alguien" },
    { palabra: "energía", significado: "La capacidad de realizar un trabajo" },
    { palabra: "estudiar", significado: "Aprender sobre algo leyendo, observando o experimentando" },
    { palabra: "efecto", significado: "El resultado de una acción o evento" },
    { palabra: "euforia", significado: "Un estado de gran felicidad y emoción" },
    { palabra: "error", significado: "Un acto o decisión equivocado" },
    { palabra: "experiencia", significado: "El conocimiento o la habilidad que se adquiere a través de la práctica o el conocimiento" },
    { palabra: "eterno", significado: "Que dura para siempre" },
    { palabra: "escena", significado: "Un lugar o lugar de acción" },
    { palabra: "escritura", significado: "El proceso de escribir" },
    { palabra: "encantar", significado: "Atraer o fascinar a alguien" },
    { palabra: "ecosistema", significado: "Un sistema natural formado por organismos vivos y su entorno" },
    { palabra: "ejercicio", significado: "La actividad física que se realiza para mantenerse sano" },
    { palabra: "eje", significado: "Una línea imaginaria que atraviesa el centro de un objeto y lo divide en dos partes iguales" },
    { palabra: "enfocar", significado: "Concentrar la atención en algo" },
    { palabra: "elegir", significado: "Decidir cuál de dos o más cosas es la mejor" },
    { palabra: "equilibrio", significado: "El estado de algo que está nivelado o equilibrado" },
    { palabra: "enigma", significado: "Un problema o pregunta que es difícil de comprender o resolver" },
    { palabra: "estilo", significado: "Una manera particular de hacer algo o de vestirse" },
    { palabra: "encontrar", significado: "Descubrir algo que estaba escondido o perdido" },
    { palabra: "esconder", significado: "Colocar algo en un lugar donde no se pueda ver" },
    { palabra: "estirar", significado: "Hacer que algo sea más largo o más grande" },
    { palabra: "espejo", significado: "Una superficie lisa que refleja la luz" },
    { palabra: "esmeralda", significado: "Una piedra preciosa verde" },
    { palabra: "esencia", significado: "La parte más importante o significativa de algo" },
    { palabra: "elevado", significado: "Que está en un nivel alto" },
    { palabra: "emoción", significado: "Una sensación fuerte que afecta al cuerpo y la mente" },
    { palabra: "evolucionar", significado: "Cambiar o desarrollarse gradualmente con el tiempo" },
    { palabra: "examinar", significado: "Mirar algo cuidadosamente para entenderlo mejor" },
    { palabra: "enfermo", significado: "Que no está sano" },
    { palabra: "esperanza", significado: "El deseo de que algo bueno suceda" },
    { palabra: "encender", significado: "Hacer que algo se encienda o se vuelva brillante" },
    { palabra: "emoción", significado: "Una sensación fuerte que afecta al cuerpo y la mente" },
    { palabra: "explicar", significado: "Dar información sobre algo para que sea más fácil de entender" },
    { palabra: "esmero", significado: "Una atención cuidadosa a los detalles" },
    { palabra: "estudio", significado: "El proceso de aprender sobre algo leyendo, observando o experimentando" },
    { palabra: "edificio", significado: "Una estructura construida para albergar personas u otras cosas" },
    { palabra: "ejemplar", significado: "Un ejemplo de algo" },
    { palabra: "enorme", significado: "Muy grande" },
    { palabra: "ejecutar", significado: "Hacer algo o completar una tarea" },
    { palabra: "encajar", significado: "Hacer que algo encaje en otro lugar" },
    { palabra: "enseñar", significado: "Transmitir conocimientos o habilidades a alguien" },
    { palabra: "establecer", significado: "Poner algo en su lugar o posición" }
];



export const F = [{
    palabra: "flor", significado: "Una planta con pétalos, tallo y raíz"
},
{ palabra: "felicidad", significado: "Un estado de ánimo de alegría y satisfacción" },
{ palabra: "fuerte", significado: "Que tiene mucha fuerza física o mental" },
{ palabra: "fuego", significado: "Una reacción química que produce luz, calor y llamas" },
{ palabra: "fácil", significado: "Que se puede hacer sin mucho esfuerzo" },
{ palabra: "fresco", significado: "Que tiene una temperatura fría o moderada" },
{ palabra: "fiesta", significado: "Una celebración o reunión social" },
{ palabra: "fantasía", significado: "Un sueño o una visión que es imposible o irreal" },
{ palabra: "fruta", significado: "El órgano comestible de una planta que contiene semillas" },
{ palabra: "forma", significado: "La apariencia externa de algo" },
{ palabra: "flotar", significado: "Permanecer en la superficie del agua sin hundirse" },
{ palabra: "famoso", significado: "Conocido por muchas personas" },
{ palabra: "fuente", significado: "Un lugar de donde viene algo, como agua o información" },
{ palabra: "fragancia", significado: "Un olor agradable" },
{ palabra: "feroz", significado: "Que es violento o agresivo" },
{ palabra: "frente", significado: "La parte frontal de algo" },
{ palabra: "festejar", significado: "Celebrar algo con alegría" },
{ palabra: "frescura", significado: "La calidad de ser fresco" },
{ palabra: "fusión", significado: "El proceso de combinar dos cosas para formar una nueva cosa" },
{ palabra: "frío", significado: "Que tiene una temperatura baja" },
{ palabra: "fiel", significado: "Que es leal o confiable" },
{ palabra: "fluir", significado: "Mover o moverse de manera suave y continua" },
{ palabra: "felpa", significado: "Una tela suave con un pelo corto y esponjoso" },
{ palabra: "frecuente", significado: "Que sucede a menudo" },
{ palabra: "frenesí", significado: "Un estado de gran excitación o agitación" },
{ palabra: "fundir", significado: "Calentar algo hasta que se derrita" },
{ palabra: "fotografía", significado: "La técnica de tomar imágenes con luz" },
{ palabra: "furia", significado: "Un sentimiento de ira o enojo intenso" },
{ palabra: "fortaleza", significado: "Una fortaleza o ciudadela fortificada" },
{ palabra: "filosofía", significado: "El estudio de los principios fundamentales de la realidad, la existencia y el conocimiento" },
{ palabra: "fiel", significado: "Que es leal o confiable" },
{ palabra: "frenético", significado: "Que es muy activo o agitado" },
{ palabra: "foso", significado: "Un agujero profundo que se cava alrededor de algo para protegerlo" },
{ palabra: "frontera", significado: "La línea que separa dos países o territorios" },
{ palabra: "fino", significado: "Que tiene una calidad superior" },
{ palabra: "fundación", significado: "La base o el principio de algo" },
{ palabra: "llama", significado: "Una columna de fuego que se produce por la combustión" },
{ palabra: "frágil", significado: "Que se rompe fácilmente" },
{ palabra: "freír", significado: "Cocinar algo en aceite caliente" },
{ palabra: "feroz", significado: "Que es violento o agresivo" },
{ palabra: "forjar", significado: "Crear algo trabajando un material en caliente" },
{ palabra: "febrero", significado: "El segundo mes del año en el calendario gregoriano y juliano, con 28 días en años comunes y 29 días en años bisiestos." },
{ palabra: "floración", significado: "El proceso de florecer" },
{ palabra: "finura", significado: "La calidad de ser fino o delicado" },
{ palabra: "frenar", significado: "Hacer que algo se detenga o vaya más despacio" },
{ palabra: "fluctuar", significado: "Cambiar de manera irregular o inconstante" },
{ palabra: "fuerte", significado: "Que tiene mucha fuerza física o mental" },
{ palabra: "frescura", significado: "La calidad de ser fresco" },
{ palabra: "fascinante", significado: "Que despierta la curiosidad y el interés" },
{ palabra: "fugaz", significado: "Que dura poco tiempo" }]


export const G =  [
    { palabra: "año", significado: "Un período de 365 días" },
    { palabra: "girar", significado: "Mover algo en un círculo" },
    { palabra: "gris", significado: "Un color que es una mezcla de blanco y negro" },
    { palabra: "gritar", significado: "Emitir un sonido fuerte y repentino" },
    { palabra: "guía", significado: "Una persona que muestra a otros el camino" },
    { palabra: "gusto", significado: "La capacidad de percibir el sabor" },
    { palabra: "gemelo", significado: "Uno de dos hermanos nacidos al mismo tiempo" },
    { palabra: "gaviota", significado: "Un ave marina con alas largas y blancas" },
    { palabra: "guardián", significado: "Una persona que protege a alguien o algo" },
    { palabra: "gritar", significado: "Emitir un sonido fuerte y repentino" },
    { palabra: "galleta", significado: "Un pequeño pastel plano que se puede comer como refrigerio o postre" },
    { palabra: "gorro", significado: "Una prenda de vestir que se lleva en la cabeza" },
    { palabra: "gracia", significado: "Elegancia y belleza de movimiento" },
    { palabra: "grupo", significado: "Un conjunto de personas o cosas que están unidas por una característica común" },
    { palabra: "genuino", significado: "Que es real y no falso" },
    { palabra: "galaxia", significado: "Una gran colección de estrellas, nubes de gas y polvo que están unidas por la gravedad" },
    { palabra: "garaje", significado: "Un edificio donde se guarda un coche" },
    { palabra: "granizo", significado: "Pequeñas esferas de hielo que caen del cielo durante una tormenta" },
    { palabra: "gema", significado: "Una piedra preciosa" },
    { palabra: "gruñir", significado: "Emitir un sonido bajo y profundo" },
    { palabra: "gesto", significado: "Un movimiento del cuerpo que expresa una idea o emoción" },
    { palabra: "goma", significado: "Un material flexible que se puede usar para hacer muchos objetos diferentes" },
    { palabra: "gritar", significado: "Emitir un sonido fuerte y repentino" },
    { palabra: "gozo", significado: "Un sentimiento de gran alegría" },
    { palabra: "grasa", significado: "Una sustancia aceitosa que se encuentra en los animales y las plantas" },
    { palabra: "giro", significado: "Un movimiento circular" },
    { palabra: "glacial", significado: "Que se relaciona con los glaciares" },
    { palabra: "guiño", significado: "Un movimiento rápido del ojo que se usa para expresar amistad o coquetería" },
    { palabra: "golpe", significado: "Un movimiento repentino de la mano o el brazo que causa daño" },
    { palabra: "garantía", significado: "Una promesa de que algo es cierto o de que algo se hará" },
    { palabra: "gesticular", significado: "Usar los gestos para expresar ideas o emociones" },
    { palabra: "galleta", significado: "Un pequeño pastel plano que se puede comer como refrigerio o postre" },
    { palabra: "grácil", significado: "Que es delgado y elegante" },
    { palabra: "germinar", significado: "Crecer a partir de una semilla" },
    { palabra: "guitarrista", significado: "Una persona que toca la guitarra" },
    { palabra: "garra", significado: "Una uña larga y afilada que se encuentra en las aves, los mamíferos y los reptiles" },
    { palabra: "gélido", significado: "Que es muy frío" },
    { palabra: "grano", significado: "Una pequeña partícula de una sustancia sólida" },
    { palabra: "guerrero", significado: "Una persona que lucha en la guerra" },
    { palabra: "gratitud", significado: "El sentimiento de agradecimiento" },
    { palabra: "grisáceo", significado: "Que tiene un color grisáceo" },
    { palabra: "genuinidad", significado: "La calidad de ser genuino" }
  ];

  export const H =  [
    { palabra: "hola", significado: "Una expresión de saludo" },
    { palabra: "huevo", significado: "Una célula reproductiva de los animales vertebrados" },
    { palabra: "hora", significado: "Un período de tiempo de sesenta minutos" },
    { palabra: "héroe", significado: "Una persona que es admirada por sus acciones valientes o heroicas" },
    { palabra: "hoja", significado: "Una parte plana y delgada de una planta" },
    { palabra: "habitación", significado: "Un espacio cerrado dentro de un edificio" },
    { palabra: "hermano", significado: "Un hijo del mismo padre y madre" },
    { palabra: "hacer", significado: "Realizar una acción" },
    { palabra: "hambre", significado: "La necesidad de comer" },
    { palabra: "habilidad", significado: "La capacidad de hacer algo bien" },
    { palabra: "herida", significado: "Un daño físico causado por una lesión" },
    { palabra: "hombre", significado: "Un ser humano adulto del sexo masculino" },
    { palabra: "humano", significado: "Que pertenece a la especie humana" },
    { palabra: "hermoso", significado: "Que es agradable a la vista" },
    { palabra: "hierba", significado: "Una planta con tallos delgados y hojas planas" },
    { palabra: "historia", significado: "Un relato de eventos reales o ficticios" },
    { palabra: "divertido", significado: "Que causa risa" },
    { palabra: "hélice", significado: "Una estructura en forma de tornillo que se usa para generar movimiento" },
    { palabra: "hora", significado: "Un período de tiempo de sesenta minutos" },
    { palabra: "harina", significado: "Un polvo fino hecho de granos molidos" },
    { palabra: "hablar", significado: "Usar el lenguaje para comunicarse" },
    { palabra: "hondo", significado: "Que tiene mucha profundidad" },
    { palabra: "horizonte", significado: "La línea donde el cielo parece encontrarse con la tierra" },
    { palabra: "higiene", significado: "La práctica de mantener limpio el cuerpo y el entorno" },
    { palabra: "hacha", significado: "Una herramienta con una hoja afilada en un extremo y un mango en el otro" },
    { palabra: "hormiga", significado: "Un insecto pequeño y social que vive en colonias" },
    { palabra: "hervir", significado: "Calentar algo hasta que se convierta en un líquido" },
    { palabra: "herramienta", significado: "Un objeto que se utiliza para hacer un trabajo" },
    { palabra: "huir", significado: "Correr lejos de un peligro" },
    { palabra: "huracán", significado: "Un ciclón tropical con vientos de más de 119 kilómetros por hora" },
    { palabra: "híbrido", significado: "Un organismo que es el resultado del cruce de dos especies diferentes" },
    { palabra: "hongo", significado: "Un organismo eucariota que no tiene hojas, flores ni semillas" },
    { palabra: "habilidad", significado: "La capacidad de hacer algo bien" },
    { palabra: "huraño", significado: "Que es tímido o reservado" },
    { palabra: "hogar", significado: "El lugar donde una persona vive" },
    { palabra: "hacer", significado: "Realizar una acción" },
    { palabra: "halcón", significado: "Un ave rapaz con alas largas y puntiagudas" },
    { palabra: "hinchado", significado: "Que está lleno de aire o líquido" },
    { palabra: "heredar", significado: "Obtener algo como propiedad después de la muerte de otra persona" },
    { palabra: "hábil", significado: "Que es capaz de hacer algo bien" },
    { palabra: "hundir", significado: "Hacer que algo se hunda" },
    { palabra: "hormigueo", significado: "Una sensación de hormigueo en la piel" },
    { palabra: "hostil", significado: "Que es enemigo o contrario" },
    { palabra: "huella", significado: "Una marca dejada por un pie o una pata" },
    { palabra: "helado", significado: "Un alimento congelado que se hace con leche, crema y azúcar" },
    { palabra: "hilo", significado: "Una hebra fina y larga de un material como la lana, el algodón o el seda" },
    { palabra: "humildad", significado: "La calidad de ser modesto y respetuoso" },
    { palabra: "homenaje", significado: "Un acto de agradecimiento o tributo" },
    { palabra: "hospital", significado: "Un edificio donde se atiende a las personas enfermas o heridas" },
    { palabra: "hiperactivo", significado: "Que tiene un exceso de energía y es difícil de controlar" }
  ];

export const I = [ { palabra: "invisible", significado: "Que no puede ser visto" },
{ palabra: "invitar", significado: "Pedir a alguien que venga a un lugar o evento" },
{ palabra: "ira", significado: "Un sentimiento de enojo o furia" },
{ palabra: "impacto", significado: "El efecto de algo" },
{ palabra: "inusual", significado: "Que no es común o corriente" },
{ palabra: "inquietud", significado: "Un sentimiento de ansiedad o preocupación" },
{ palabra: "inmenso", significado: "Muy grande o vasto" },
{ palabra: "inicio", significado: "El comienzo de algo" },
{ palabra: "intuir", significado: "Saber algo sin tener pruebas" },
{ palabra: "imagen", significado: "Una representación visual de algo" },
{ palabra: "inglés", significado: "Un idioma que se habla en el Reino Unido, Estados Unidos, Canadá, Australia y Nueva Zelanda" },
{ palabra: "infinito", significado: "Sin fin o límite" },
{ palabra: "irreal", significado: "Que no es real o verdadero" },
{ palabra: "imitación", significado: "El acto de copiar las acciones o palabras de otra persona" },
{ palabra: "investigar", significado: "Examinar algo cuidadosamente para obtener información" },
{ palabra: "indicación", significado: "Una señal o sugerencia de algo" },
{ palabra: "imitar", significado: "Copiar las acciones o palabras de otra persona" },
{ palabra: "inflar", significado: "Hacer que algo sea más grande llenando de aire o gas" },
{ palabra: "inscribir", significado: "Escribir algo en un lugar o superficie" },
{ palabra: "inodoro", significado: "Que no tiene olor" },
{ palabra: "iniciar", significado: "Empezar algo" },
{ palabra: "interactuar", significado: "Comunicarse o actuar con otra persona o cosa" },
{ palabra: "inmediato", significado: "Que sucede o se hace inmediatamente" },
{ palabra: "invadir", significado: "Entrar en un lugar o territorio sin permiso" },
{ palabra: "incluir", significado: "Añadir algo a un grupo o colección" },
{ palabra: "infusión", significado: "Un líquido que se ha hecho remojando algo en agua" },
{ palabra: "ingreso", significado: "El acto de entrar en un lugar" },
{ palabra: "ilusión", significado: "Una falsa impresión o creencia" },
{ palabra: "interesante", significado: "Que despierta la curiosidad o el interés" },
{ palabra: "incendio", significado: "Un fuego que se extiende rápidamente" },
{ palabra: "incidir", significado: "Tener un efecto o influencia en algo" },
{ palabra: "inusual", significado: "Que no es común o corriente" },
{ palabra: "inquietud", significado: "Un sentimiento de ansiedad o preocupación" },
{ palabra: "impactante", significado: "Que tiene un gran efecto o impacto" },
{ palabra: "intención", significado: "El deseo o propósito de hacer algo" },
{ palabra: "insomnio", significado: "La incapacidad de dormir" },
{ palabra: "intenso", significado: "Muy fuerte o intenso" },
{ palabra: "impulso", significado: "Una fuerza que impulsa a alguien a hacer algo" }
];

  export const J =  [
    { palabra: "juego", significado: "Una actividad realizada para la diversión o el entretenimiento" },
    { palabra: "joya", significado: "Una piedra preciosa o un adorno valioso" },
    { palabra: "jirafa", significado: "Un mamífero de cuello largo que se encuentra en África" },
    { palabra: "joven", significado: "Que está en la primera etapa de la vida" },
    { palabra: "jadeo", significado: "Respirar con dificultad y rapidez" },
    { palabra: "jefe", significado: "La persona en la posición de autoridad más alta" },
    { palabra: "joroba", significado: "Una protuberancia en la espalda de ciertos animales" },
    { palabra: "jugar", significado: "Participar en un juego o actividad recreativa" },
    { palabra: "jirafa", significado: "Un mamífero de cuello largo que se encuentra en África" },
    { palabra: "jabón", significado: "Una sustancia utilizada para lavar y limpiar" },
    { palabra: "jardín", significado: "Un área con plantas y flores cultivadas" },
    { palabra: "jarra", significado: "Un recipiente grande con asa y boca ancha" },
    { palabra: "jubilado", significado: "Que ha dejado de trabajar después de alcanzar una cierta edad" },
    { palabra: "juguete", significado: "Un objeto para que los niños jueguen" },
    { palabra: "jirafa", significado: "Un mamífero de cuello largo que se encuentra en África" },
    { palabra: "jueves", significado: "El quinto día de la semana" },
    { palabra: "jaula", significado: "Un recinto con barras utilizado para contener animales" },
    { palabra: "juego", significado: "Una actividad realizada para la diversión o el entretenimiento" },
    { palabra: "jubilo", significado: "Una gran alegría o felicidad" },
    { palabra: "jugar", significado: "Participar en un juego o actividad recreativa" },
    { palabra: "jirafa", significado: "Un mamífero de cuello largo que se encuentra en África" },
    { palabra: "jabalí", significado: "Un cerdo salvaje de gran tamaño" },
    { palabra: "jirafa", significado: "Un mamífero de cuello largo que se encuentra en África" },
    { palabra: "junto", significado: "En compañía de o al lado de alguien o algo" },
    { palabra: "joven", significado: "Que está en la primera etapa de la vida" },
    { palabra: "jueves", significado: "El quinto día de la semana" },
    { palabra: "jabalí", significado: "Un cerdo salvaje de gran tamaño" },
    { palabra: "jirafa", significado: "Un mamífero de cuello largo que se encuentra en África" },
    { palabra: "juego", significado: "Una actividad realizada para la diversión o el entretenimiento" },
    { palabra: "jubilo", significado: "Una gran alegría o felicidad" },
    { palabra: "jugar", significado: "Participar en un juego o actividad recreativa" },
    { palabra: "jirafa", significado: "Un mamífero de cuello largo que se encuentra en África" },
    { palabra: "jabalí", significado: "Un cerdo salvaje de gran tamaño" },
    { palabra: "junto", significado: "En compañía de o al lado de alguien o algo" },
    { palabra: "joven", significado: "Que está en la primera etapa de la vida" },
    { palabra: "jueves", significado: "El quinto día de la semana" },
    { palabra: "jirafa", significado: "Un mamífero de cuello largo que se encuentra en África" },
    { palabra: "jabalí", significado: "Un cerdo salvaje de gran tamaño" },
    { palabra: "juego", significado: "Una actividad realizada para la diversión o el entretenimiento" },
    { palabra: "jubilo", significado: "Una gran alegría o felicidad" },
    { palabra: "jugar", significado: "Participar en un juego o actividad recreativa" },
    { palabra: "jirafa", significado: "Un mamífero de cuello largo que se encuentra en África" },
    { palabra: "jabalí", significado: "Un cerdo salvaje de gran tamaño" },
    { palabra: "junto", significado: "En compañía de o al lado de alguien o algo" },
    { palabra: "joven", significado: "Que está en la primera etapa de la vida" },
    { palabra: "jueves", significado: "El quinto día de la semana" },
    { palabra: "jirafa", significado: "Un mamífero de cuello largo que se encuentra en África" },
    { palabra: "jabalí", significado: "Un cerdo salvaje de gran tamaño" },
    { palabra: "juego", significado: "Una actividad realizada para la diversión o el entretenimiento" },
    { palabra: "jubilo", significado: "Una gran alegría o felicidad" },
    { palabra: "jugar", significado: "Participar en un juego o actividad recreativa" },
    { palabra: "jirafa", significado: "Un mamífero de cuello largo que se encuentra en África" }
  ];

  
  


  export const K =[
    {
      palabra: "kilómetro",
      significado: "Una unidad de longitud que equivale a 1000 metros."
    },
    {
      palabra: "kiosco",
      significado: "Una tienda pequeña que vende periódicos, revistas, dulces, golosinas, etc."
    },
    {
      palabra: "karate",
      significado: "Un arte marcial japonés que se caracteriza por su uso de golpes y patadas."
    },
    {
      palabra: "karaoke",
      significado: "Una actividad en la que las personas cantan canciones con la ayuda de una máquina que proporciona la música de fondo."
    },
    {
      palabra: "karma",
      significado: "La creencia de que las acciones de una persona en esta vida tendrán consecuencias en la próxima vida."
    },
    {
      palabra: "ketchup",
      significado: "Una salsa espesa y roja hecha de tomates, vinagre, azúcar, sal y especias."
    },
    {
      palabra: "kilo",
      significado: "Una unidad de masa que equivale a 1000 gramos."
    },
    {
      palabra: "kiwi",
      significado: "Una fruta redonda y verde que es nativa de Nueva Zelanda."
    },
    {
      palabra: "koala",
      significado: "Un marsupial que es nativo de Australia."
    },
    {
      palabra: "krypton",
      significado: "Un planeta ficticio en el que nació Superman."
    },
    {
      palabra: "kilt",
      significado: "Una falda larga y escocesa que es usada por los hombres."
    },
    {
      palabra: "karateca",
      significado: "Una persona que practica el arte marcial del karate."
    },
    {
      palabra: "kioskero",
      significado: "Una persona que trabaja en un kiosco."
    },
    {
      palabra: "kilovatio",
      significado: "Una unidad de potencia eléctrica que equivale a 1000 vatios."
    },
    {
      palabra: "kafkiano",
      significado: "Que es característico de la obra del escritor Franz Kafka."
    },
    {
      palabra: "kit",
      significado: "Un conjunto de herramientas o materiales que se utilizan para realizar una tarea específica."
    },
    {
      palabra: "kryptonita",
      significado: "Una piedra ficticia que debilita a Superman."
    },
    {
      palabra: "kefir",
      significado: "Una bebida fermentada hecha de leche."
    }
  ];