

export const A = [
    { palabra: "Amigo", significado: "una persona con la que uno tiene una relación de afecto y confianza." },
    { palabra: "Amar", significado: "sentir un gran afecto y cariño por alguien." },
    { palabra: "Avión", significado: "una máquina voladora más pesada que el aire, impulsada por uno o más motores." },
    { palabra: "Arena", significado: "un material granular que se compone de partículas pequeñas de roca, conchas y otros materiales." },
    { palabra: "Almohada", significado: "una almohada es un objeto blandito que se usa para apoyar la cabeza cuando se duerme." },
    { palabra: "Ardilla", significado: "una pequeña criatura mamífera que tiene una cola larga y una cola esponjosa." },
    { palabra: "Alegre", significado: "que siente o expresa alegría." },
    { palabra: "Alimento", significado: "cualquier sustancia que proporciona los nutrientes necesarios para la vida." },
    { palabra: "Aventura", significado: "una experiencia emocionante e inesperada." },
    { palabra: "Amanecer", significado: "el momento del día en que el sol comienza a salir por el horizonte." },
    { palabra: "Agricultura", significado: "el cultivo de plantas y el cuidado de los animales para obtener alimentos." },
    { palabra: "Abrazo", significado: "un gesto de afecto en el que dos personas se abrazan con los brazos." },
    { palabra: "Acuático", significado: "que vive en el agua." },
    { palabra: "Agua", significado: "un líquido incoloro, inodoro e insípido que es esencial para la vida." },
    { palabra: "Artista", significado: "una persona que crea obras de arte, como pinturas, esculturas, música o literatura." },
    { palabra: "Anillo", significado: "una pieza de joyería que se lleva en el dedo y que a menudo tiene forma de círculo." },
    { palabra: "Asombro", significado: "una sensación de asombro o sorpresa." },
    { palabra: "Atardecer", significado: "el momento del día en que el sol se pone por el horizonte." },
    { palabra: "Azul", significado: "un color que es similar al color del cielo y del mar." },
    { palabra: "Aroma", significado: "un olor agradable." },
    { palabra: "Abundante", significado: "que tiene mucho de algo." },
    { palabra: "Anaranjado", significado: "un color que es similar al color de las naranjas y los melones." },
    { palabra: "Adolescente", significado: "una persona que tiene entre 13 y 19 años de edad." },
    { palabra: "Antiguo", significado: "que existe desde hace mucho tiempo." },
    { palabra: "Astro", significado: "un cuerpo celeste, como un planeta, una estrella o una galaxia." },
    { palabra: "Aprender", significado: "adquirir conocimientos o habilidades." },
    { palabra: "Altura", significado: "la distancia desde el punto más bajo de algo hasta su punto más alto." },
    { palabra: "Abierto", significado: "que no está cerrado." },
    { palabra: "Aire", significado: "la mezcla de gases que rodea la Tierra." },
    { palabra: "Animal", significado: "un organismo vivo que no es una planta y que tiene un cuerpo con un esqueleto interno." },
    { palabra: "Amoroso", significado: "que siente o expresa amor." },
    { palabra: "Actividad", significado: "una acción o un proceso que se lleva a cabo." },
    { palabra: "Agregar", significado: "aumentar la cantidad de algo." },
    { palabra: "Adorable", significado: "que es muy agradable o encantador." },
    { palabra: "Árbol", significado: "una planta leñosa que tiene un tronco alto y ramas." },
    { palabra: "Acelerar", significado: "aumentar la velocidad de algo." },
    { palabra: "Anhelo", significado: "un deseo intenso de algo." },
    { palabra: "Aullido", significado: "un sonido agudo que hacen los lobos y otros animales." },
    { palabra: "Aldea", significado: "un pequeño pueblo." },
    { palabra: "Apetito", significado: "el deseo de comer." },
    { palabra: "Agotado", significado: "cansado o fatigado." },
    { palabra: "Adivinar", significado: "intentar descubrir algo sin tener información sobre ello." },
    { palabra: "Amable", significado: "que es cortés y considerado con los demás." },
    { palabra: "Alegría", significado: "una sensación de felicidad y satisfacción." },
    { palabra: "Anunciar", significado: "hacer público algo." },
    { palabra: "Armadura", significado: "una pieza de ropa protectora que se usa para proteger el cuerpo de lesiones." },
    { palabra: "Atleta", significado: "una persona que compite en deportes." },
    { palabra: "Adornar", significado: "decorar o embellecer algo." },
    { palabra: "Apretado", significado: "que está cerca o muy unido." },
    { palabra: "Aislado", significado: "que está separado o aislado de otros." }
];

export const B = [
    { palabra: "Bosque", significado: "una gran extensión de tierra cubierta de árboles" },
    { palabra: "Brillar", significado: "emitir luz" },
    { palabra: "Bucear", significado: "sumergirse bajo el agua para nadar o explorar" },
    { palabra: "Bola", significado: "una forma redonda" },
    { palabra: "Bicicleta", significado: "un vehículo de dos ruedas que se impulsa con los pies" },
    { palabra: "Bello", significado: "hermoso" },
    { palabra: "Barco", significado: "una embarcación que se utiliza para navegar por el agua" },
    { palabra: "Bebé", significado: "un recién nacido" },
    { palabra: "Bilingüe", significado: "que habla dos idiomas" },
    { palabra: "Blanco", significado: "el color de la nieve y la leche" },
    { palabra: "Brisa", significado: "una brisa ligera" },
    { palabra: "Bocado", significado: "una pequeña porción de comida" },
    { palabra: "Bastón", significado: "un palo largo que se usa para apoyarse al caminar" },
    { palabra: "Biblioteca", significado: "una colección de libros que se guarda en un edificio" },
    { palabra: "Burbuja", significado: "una esfera de gas rodeada de una fina película de líquido" },
    { palabra: "Bailar", significado: "moverse al ritmo de la música" },
    { palabra: "Banco", significado: "un asiento largo" },
    { palabra: "Botella", significado: "un recipiente cerrado de vidrio o plástico que se usa para contener líquidos" },
    { palabra: "Búho", significado: "un ave nocturna con grandes ojos" },
    { palabra: "Broma", significado: "una historia divertida" },
    { palabra: "Belleza", significado: "la cualidad de ser hermoso" },
    { palabra: "Burro", significado: "un mamífero domesticado con orejas largas y una cola larga" },
    { palabra: "Baloncesto", significado: "un deporte que se juega entre dos equipos de cinco jugadores cada uno, que intentan introducir una pelota en la canasta del equipo contrario" },
    { palabra: "Banderín", significado: "una pequeña bandera" },
    { palabra: "Beso", significado: "un gesto de cariño que consiste en poner los labios sobre los labios de otra persona" },
    { palabra: "Bulevar", significado: "una avenida ancha" },
    { palabra: "Botánico", significado: "una persona que estudia las plantas" },
    { palabra: "Broche", significado: "una joya que se usa para sujetar la ropa" },
    { palabra: "Botánica", significado: "la ciencia que estudia las plantas" },
    { palabra: "Batalla", significado: "un combate entre dos o más grupos de personas" },
    { palabra: "Bruja", significado: "una mujer que se cree que practica la magia" },
    { palabra: "Bolso", significado: "una bolsa que se lleva colgada del hombro o del brazo" },
    { palabra: "Brillo", significado: "el resplandor de algo que refleja la luz" },
    { palabra: "Borrar", significado: "eliminar algo escribiendo o pintando sobre ello" },
    { palabra: "Bocadillo", significado: "una comida ligera que se come entre horas" },
    { palabra: "Bloque", significado: "un objeto sólido de forma cúbica o rectangular" },
    { palabra: "Brújula", significado: "un instrumento que se utiliza para orientarse" },
    { palabra: "Buzón", significado: "un recipiente que se coloca en la calle para depositar el correo" },
    { palabra: "Bote", significado: "una embarcación pequeña" },
    { palabra: "Bufanda", significado: "una prenda de vestir que se lleva alrededor del cuello para abrigarse" },
    { palabra: "Bastidor", significado: "un marco de madera o metal que se utiliza para sostener la tela cuando se pinta" },
    { palabra: "Brincar", significado: "saltar" },
    { palabra: "Brocha", significado: "una herramienta que se utiliza para aplicar pintura" },
    { palabra: "Buitre", significado: "un ave carroñera" },
    { palabra: "Bombero", significado: "una persona que trabaja en un cuerpo de bomberos" },
    { palabra: "Bocanada", significado: "una cantidad de aire o líquido que se inspira o espira de una sola vez" },
    { palabra: "Bofetada", significado: "un golpe que se da con la mano abierta" },
    { palabra: "Botín", significado: "el robo o el saqueo" },
    { palabra: "Bizcocho", significado: "un pastel pequeño y esponjoso" },
    { palabra: "Bigote", significado: "el vello facial que crece sobre el labio superior" }
];

export const C = [{ palabra: "cielo", significado: "La atmósfera que rodea la Tierra" },
{ palabra: "correr", significado: "Moverse a gran velocidad con los pies" },
{ palabra: "caminar", significado: "Moverse a paso lento con los pies" },
{ palabra: "comida", significado: "Cualquier sustancia que proporciona los nutrientes necesarios para la vida" },
{ palabra: "corazón", significado: "Un órgano muscular que bombea sangre por todo el cuerpo" },
{ palabra: "castillo", significado: "Una gran estructura fortificada" },
{ palabra: "cálido", significado: "Que tiene una temperatura alta" },
{ palabra: "colina", significado: "Una elevación del terreno con una pendiente suave" },
{ palabra: "ciudad", significado: "Un área urbana grande con una población numerosa" },
{ palabra: "canto", significado: "El sonido que produce un pájaro u otro animal" },
{ palabra: "circular", significado: "Tener forma de círculo" },
{ palabra: "cebra", significado: "Un mamífero africano con rayas blancas y negras" },
{ palabra: "cerveza", significado: "Una bebida alcohólica hecha de cebada, lúpulo y levadura" },
{ palabra: "camión", significado: "Un vehículo grande con ruedas que se utiliza para transportar cargas pesadas" },
{ palabra: "caja", significado: "Un recipiente cerrado con una tapa" },
{ palabra: "cautivar", significado: "Atraer y mantener la atención de alguien" },
{ palabra: "cine", significado: "Un lugar donde se proyectan películas" },
{ palabra: "cisne", significado: "Un ave acuática grande con un cuello largo y una cola blanca" },
{ palabra: "capitán", significado: "El oficial al mando de un barco" },
{ palabra: "ciclismo", significado: "El deporte de montar en bicicleta" },
{ palabra: "cosecha", significado: "La recolección de cultivos" },
{ palabra: "cometa", significado: "Un objeto helado que orbita alrededor del Sol" },
{ palabra: "cuerpo", significado: "La estructura física de un ser vivo" },
{ palabra: "calma", significado: "La ausencia de actividad o movimiento" },
{ palabra: "curioso", significado: "Que siente curiosidad" },
{ palabra: "cocina", significado: "Una habitación de una casa donde se prepara la comida" },
{ palabra: "campana", significado: "Un objeto metálico que produce un sonido al ser golpeado" },
{ palabra: "cuento", significado: "Una historia corta" },
{ palabra: "calle", significado: "Una vía pública pavimentada que conecta diferentes partes de una ciudad" },
{ palabra: "cuadro", significado: "Una pintura o dibujo que se enmarca y se cuelga en una pared" },
{ palabra: "cactus", significado: "Una planta espinosa que crece en climas áridos" },
{ palabra: "conectar", significado: "Unir dos cosas" },
{ palabra: "criatura", significado: "Un ser vivo" },
{ palabra: "colores", significado: "Las cualidades que distinguen a los objetos por su apariencia" },
{ palabra: "crucero", significado: "Un viaje por mar" },
{ palabra: "cálido", significado: "Que tiene una temperatura agradable" },
{ palabra: "calcetín", significado: "Una prenda de vestir que se usa para cubrir los pies" },
{ palabra: "comedia", significado: "Una obra de teatro o película que tiene como objetivo hacer reír al público" },
{ palabra: "cautivar", significado: "Atraer y mantener la atención de alguien" },
{ palabra: "corriente", significado: "Un movimiento continuo de agua" },
{ palabra: "cruzar", significado: "Ir de un lado a otro de algo" },
{ palabra: "cepillo", significado: "Un objeto con cerdas que se utiliza para limpiar o aplicar algo" },
{ palabra: "calcular", significado: "Determinar el valor de algo mediante el uso de matemáticas" },
{ palabra: "crepúsculo", significado: "El período de tiempo entre el atardecer y el amanecer" },
{ palabra: "cuaderno", significado: "Un libro con páginas en blanco que se utiliza para escribir o dibujar" },
{ palabra: "cuerda", significado: "Un material flexible hecho de hilos o fibras trenzados" },
{ palabra: "caracol", significado: "Un molusco que tiene un caparazón en espiral" },
{ palabra: "cohete", significado: "Un vehículo propulsado por cohetes que se utiliza para volar en el espacio" },
{ palabra: "caja", significado: "Un recipiente cerrado con una tapa" },
{ palabra: "cofre", significado: "Un recipiente grande y cerrado que se utiliza para guardar objetos de valor" }
];

export const D = [{ palabra: "dibujo", significado: "Una representación visual de algo" },
{ palabra: "diamante", significado: "Una piedra preciosa que se caracteriza por su forma cúbica y su brillo" },
{ palabra: "deseo", significado: "Un anhelo o anhelo" },
{ palabra: "desayuno", significado: "La primera comida del día" },
{ palabra: "diversión", significado: "Una actividad que es agradable y entretenida" },
{ palabra: "dado", significado: "Un objeto pequeño y cúbico con seis caras numeradas del 1 al 6" },
{ palabra: "dulce", significado: "Un alimento que es agradablemente dulce" },
{ palabra: "dolor", significado: "Una sensación física desagradable causada por una lesión o enfermedad" },
{ palabra: "decisión", significado: "La elección de una cosa entre varias opciones" },
{ palabra: "destino", significado: "El lugar o condición a la que alguien o algo está destinado" },
{ palabra: "danza", significado: "Un movimiento corporal rítmico realizado como una forma de expresión o entretenimiento" },
{ palabra: "dedo", significado: "Una de las extremidades móviles y flexibles que se extienden desde la muñeca" },
{ palabra: "difícil", significado: "Que requiere mucha habilidad o esfuerzo" },
{ palabra: "duda", significado: "Una falta de certeza o confianza" },
{ palabra: "defensa", significado: "La acción de proteger a alguien o algo de daño" },
{ palabra: "dama", significado: "Una pieza de ajedrez que se mueve en forma de L" },
{ palabra: "diente", significado: "Una estructura dura que se encuentra en la boca y se utiliza para masticar" },
{ palabra: "deportivo", significado: "Relacionado con los deportes" },
{ palabra: "dormir", significado: "El estado de descanso profundo durante el cual la mente y el cuerpo están inactivos" },
{ palabra: "doctor", significado: "Una persona que ha completado un programa de educación médica y está autorizada para practicar medicina" },
{ palabra: "decorar", significado: "Hacer que algo sea más atractivo o agradable añadiendo elementos decorativos" },
{ palabra: "derramar", significado: "Perder líquido accidentalmente" },
{ palabra: "duna", significado: "Una colina de arena que se forma en las costas o en los desiertos" },
{ palabra: "diseño", significado: "El proceso de creación de un plan o esquema para algo" },
{ palabra: "descansar", significado: "Tomar un descanso del trabajo o la actividad" },
{ palabra: "desechar", significado: "Tirar algo que ya no se necesita o se quiere" },
{ palabra: "desfile", significado: "Una marcha pública de personas o vehículos, a menudo para celebrar un evento o ocasión especial" },
{ palabra: "dedicatoria", significado: "Una breve declaración escrita al comienzo de un libro o obra de arte, que expresa el agradecimiento del autor a una persona o personas" },
{ palabra: "dosis", significado: "La cantidad de una medicina o droga que se toma a la vez" },
{ palabra: "delgado", significado: "Que tiene una pequeña cantidad de grasa o carne" },
{ palabra: "depender", significado: "Confiar en alguien o algo para obtener apoyo o ayuda" },
{ palabra: "diferente", significado: "No igual a otra cosa" },
{ palabra: "decir", significado: "Expresar una idea o pensamiento con palabras" },
{ palabra: "desierto", significado: "Una región árida que tiene muy poca lluvia" },
{ palabra: "derrumbar", significado: "Caer o causar que algo caiga" },
{ palabra: "dieta", significado: "Un plan de alimentación diseñado para ayudar a las personas a perder peso, mantener un peso saludable o mejorar su salud" },
{ palabra: "dejar", significado: "Terminar de hacer algo o dejar de estar en un lugar" },
{ palabra: "despegar", significado: "Levantarse del suelo y comenzar a volar" },
{ palabra: "destacar", significado: "Ser más prominente o visible que otras cosas" },
{ palabra: "dado", significado: "Un objeto pequeño y cúbico con seis caras numeradas del 1 al 6" },
{ palabra: "desastre", significado: "Un evento que causa una gran destrucción o daño" },
{ palabra: "durar", significado: "Continuar durante un tiempo determinado" },
{ palabra: "decidir", significado: "Tomar una decisión sobre algo" },
{ palabra: "disfrutar", significado: "Encontrar placer en algo" },
{ palabra: "dolor", significado: "Una sensación física desagradable causada por una lesión o enfermedad" },
{ palabra: "difuminar", significado: "Hacer que algo sea menos claro o definido" },
{ palabra: "definir", significado: "Dar el significado de una palabra o frase" },
{ palabra: "devorar", significado: "Comer algo con gran rapidez y avidez" },
{ palabra: "dudar", significado: "No estar seguro de algo" }
];

export const E = [
    { palabra: "estrella", significado: "Un gran objeto celeste que brilla con su propia luz" },
    { palabra: "escuchar", significado: "Prestar atención a lo que alguien dice o hace" },
    { palabra: "elefante", significado: "Un mamífero grande con una trompa, orejas grandes y una piel gruesa" },
    { palabra: "esencia", significado: "La parte más importante o significativa de algo" },
    { palabra: "elegante", significado: "Que es bonito y elegante" },
    { palabra: "emoción", significado: "Una sensación fuerte que afecta al cuerpo y la mente" },
    { palabra: "espacio", significado: "El área que rodea a la Tierra o a cualquier otro objeto" },
    { palabra: "enseñar", significado: "Transmitir conocimientos o habilidades a alguien" },
    { palabra: "energía", significado: "La capacidad de realizar un trabajo" },
    { palabra: "estudiar", significado: "Aprender sobre algo leyendo, observando o experimentando" },
    { palabra: "efecto", significado: "El resultado de una acción o evento" },
    { palabra: "euforia", significado: "Un estado de gran felicidad y emoción" },
    { palabra: "error", significado: "Un acto o decisión equivocado" },
    { palabra: "experiencia", significado: "El conocimiento o la habilidad que se adquiere a través de la práctica o el conocimiento" },
    { palabra: "eterno", significado: "Que dura para siempre" },
    { palabra: "escena", significado: "Un lugar o lugar de acción" },
    { palabra: "escritura", significado: "El proceso de escribir" },
    { palabra: "encantar", significado: "Atraer o fascinar a alguien" },
    { palabra: "ecosistema", significado: "Un sistema natural formado por organismos vivos y su entorno" },
    { palabra: "ejercicio", significado: "La actividad física que se realiza para mantenerse sano" },
    { palabra: "eje", significado: "Una línea imaginaria que atraviesa el centro de un objeto y lo divide en dos partes iguales" },
    { palabra: "enfocar", significado: "Concentrar la atención en algo" },
    { palabra: "elegir", significado: "Decidir cuál de dos o más cosas es la mejor" },
    { palabra: "equilibrio", significado: "El estado de algo que está nivelado o equilibrado" },
    { palabra: "enigma", significado: "Un problema o pregunta que es difícil de comprender o resolver" },
    { palabra: "estilo", significado: "Una manera particular de hacer algo o de vestirse" },
    { palabra: "encontrar", significado: "Descubrir algo que estaba escondido o perdido" },
    { palabra: "esconder", significado: "Colocar algo en un lugar donde no se pueda ver" },
    { palabra: "estirar", significado: "Hacer que algo sea más largo o más grande" },
    { palabra: "espejo", significado: "Una superficie lisa que refleja la luz" },
    { palabra: "esmeralda", significado: "Una piedra preciosa verde" },
    { palabra: "esencia", significado: "La parte más importante o significativa de algo" },
    { palabra: "elevado", significado: "Que está en un nivel alto" },
    { palabra: "emoción", significado: "Una sensación fuerte que afecta al cuerpo y la mente" },
    { palabra: "evolucionar", significado: "Cambiar o desarrollarse gradualmente con el tiempo" },
    { palabra: "examinar", significado: "Mirar algo cuidadosamente para entenderlo mejor" },
    { palabra: "enfermo", significado: "Que no está sano" },
    { palabra: "esperanza", significado: "El deseo de que algo bueno suceda" },
    { palabra: "encender", significado: "Hacer que algo se encienda o se vuelva brillante" },
    { palabra: "emoción", significado: "Una sensación fuerte que afecta al cuerpo y la mente" },
    { palabra: "explicar", significado: "Dar información sobre algo para que sea más fácil de entender" },
    { palabra: "esmero", significado: "Una atención cuidadosa a los detalles" },
    { palabra: "estudio", significado: "El proceso de aprender sobre algo leyendo, observando o experimentando" },
    { palabra: "edificio", significado: "Una estructura construida para albergar personas u otras cosas" },
    { palabra: "ejemplar", significado: "Un ejemplo de algo" },
    { palabra: "enorme", significado: "Muy grande" },
    { palabra: "ejecutar", significado: "Hacer algo o completar una tarea" },
    { palabra: "encajar", significado: "Hacer que algo encaje en otro lugar" },
    { palabra: "enseñar", significado: "Transmitir conocimientos o habilidades a alguien" },
    { palabra: "establecer", significado: "Poner algo en su lugar o posición" }
];



export const F = [{
    palabra: "flor", significado: "Una planta con pétalos, tallo y raíz"
},
{ palabra: "felicidad", significado: "Un estado de ánimo de alegría y satisfacción" },
{ palabra: "fuerte", significado: "Que tiene mucha fuerza física o mental" },
{ palabra: "fuego", significado: "Una reacción química que produce luz, calor y llamas" },
{ palabra: "fácil", significado: "Que se puede hacer sin mucho esfuerzo" },
{ palabra: "fresco", significado: "Que tiene una temperatura fría o moderada" },
{ palabra: "fiesta", significado: "Una celebración o reunión social" },
{ palabra: "fantasía", significado: "Un sueño o una visión que es imposible o irreal" },
{ palabra: "fruta", significado: "El órgano comestible de una planta que contiene semillas" },
{ palabra: "forma", significado: "La apariencia externa de algo" },
{ palabra: "flotar", significado: "Permanecer en la superficie del agua sin hundirse" },
{ palabra: "famoso", significado: "Conocido por muchas personas" },
{ palabra: "fuente", significado: "Un lugar de donde viene algo, como agua o información" },
{ palabra: "fragancia", significado: "Un olor agradable" },
{ palabra: "feroz", significado: "Que es violento o agresivo" },
{ palabra: "frente", significado: "La parte frontal de algo" },
{ palabra: "festejar", significado: "Celebrar algo con alegría" },
{ palabra: "frescura", significado: "La calidad de ser fresco" },
{ palabra: "fusión", significado: "El proceso de combinar dos cosas para formar una nueva cosa" },
{ palabra: "frío", significado: "Que tiene una temperatura baja" },
{ palabra: "fiel", significado: "Que es leal o confiable" },
{ palabra: "fluir", significado: "Mover o moverse de manera suave y continua" },
{ palabra: "felpa", significado: "Una tela suave con un pelo corto y esponjoso" },
{ palabra: "frecuente", significado: "Que sucede a menudo" },
{ palabra: "frenesí", significado: "Un estado de gran excitación o agitación" },
{ palabra: "fundir", significado: "Calentar algo hasta que se derrita" },
{ palabra: "fotografía", significado: "La técnica de tomar imágenes con luz" },
{ palabra: "furia", significado: "Un sentimiento de ira o enojo intenso" },
{ palabra: "fortaleza", significado: "Una fortaleza o ciudadela fortificada" },
{ palabra: "filosofía", significado: "El estudio de los principios fundamentales de la realidad, la existencia y el conocimiento" },
{ palabra: "fiel", significado: "Que es leal o confiable" },
{ palabra: "frenético", significado: "Que es muy activo o agitado" },
{ palabra: "foso", significado: "Un agujero profundo que se cava alrededor de algo para protegerlo" },
{ palabra: "frontera", significado: "La línea que separa dos países o territorios" },
{ palabra: "fino", significado: "Que tiene una calidad superior" },
{ palabra: "fundación", significado: "La base o el principio de algo" },
{ palabra: "llama", significado: "Una columna de fuego que se produce por la combustión" },
{ palabra: "frágil", significado: "Que se rompe fácilmente" },
{ palabra: "freír", significado: "Cocinar algo en aceite caliente" },
{ palabra: "feroz", significado: "Que es violento o agresivo" },
{ palabra: "forjar", significado: "Crear algo trabajando un material en caliente" },
{ palabra: "febrero", significado: "El segundo mes del año en el calendario gregoriano y juliano, con 28 días en años comunes y 29 días en años bisiestos." },
{ palabra: "floración", significado: "El proceso de florecer" },
{ palabra: "finura", significado: "La calidad de ser fino o delicado" },
{ palabra: "frenar", significado: "Hacer que algo se detenga o vaya más despacio" },
{ palabra: "fluctuar", significado: "Cambiar de manera irregular o inconstante" },
{ palabra: "fuerte", significado: "Que tiene mucha fuerza física o mental" },
{ palabra: "frescura", significado: "La calidad de ser fresco" },
{ palabra: "fascinante", significado: "Que despierta la curiosidad y el interés" },
{ palabra: "fugaz", significado: "Que dura poco tiempo" }]